#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORLDCLOCKVS
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ClockVS")]
	public partial class ClockVSDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertclock(clock instance);
    partial void Updateclock(clock instance);
    partial void Deleteclock(clock instance);
    partial void InsertHM(HM instance);
    partial void UpdateHM(HM instance);
    partial void DeleteHM(HM instance);
    partial void InsertSetAlarm(SetAlarm instance);
    partial void UpdateSetAlarm(SetAlarm instance);
    partial void DeleteSetAlarm(SetAlarm instance);
    partial void InsertSetAlarm1(SetAlarm1 instance);
    partial void UpdateSetAlarm1(SetAlarm1 instance);
    partial void DeleteSetAlarm1(SetAlarm1 instance);
    partial void InsertWorld_Clock(World_Clock instance);
    partial void UpdateWorld_Clock(World_Clock instance);
    partial void DeleteWorld_Clock(World_Clock instance);
    partial void InsertNamaz_Timer(Namaz_Timer instance);
    partial void UpdateNamaz_Timer(Namaz_Timer instance);
    partial void DeleteNamaz_Timer(Namaz_Timer instance);
    partial void Insertloginn(loginn instance);
    partial void Updateloginn(loginn instance);
    partial void Deleteloginn(loginn instance);
    #endregion
		
		public ClockVSDataContext() : 
				base(global::WORLDCLOCKVS.Properties.Settings.Default.ClockVSConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ClockVSDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ClockVSDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ClockVSDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ClockVSDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<clock> clocks
		{
			get
			{
				return this.GetTable<clock>();
			}
		}
		
		public System.Data.Linq.Table<HM> HMs
		{
			get
			{
				return this.GetTable<HM>();
			}
		}
		
		public System.Data.Linq.Table<SetAlarm> SetAlarms
		{
			get
			{
				return this.GetTable<SetAlarm>();
			}
		}
		
		public System.Data.Linq.Table<SetAlarm1> SetAlarm1s
		{
			get
			{
				return this.GetTable<SetAlarm1>();
			}
		}
		
		public System.Data.Linq.Table<World_Clock> World_Clocks
		{
			get
			{
				return this.GetTable<World_Clock>();
			}
		}
		
		public System.Data.Linq.Table<Namaz_Timer> Namaz_Timers
		{
			get
			{
				return this.GetTable<Namaz_Timer>();
			}
		}
		
		public System.Data.Linq.Table<loginn> loginns
		{
			get
			{
				return this.GetTable<loginn>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.clock")]
	public partial class clock : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _clock_name;
		
		private string _time_zone;
		
		private System.Nullable<System.TimeSpan> _times;
		
		private System.Nullable<System.DateTime> _date;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onclock_nameChanging(string value);
    partial void Onclock_nameChanged();
    partial void Ontime_zoneChanging(string value);
    partial void Ontime_zoneChanged();
    partial void OntimesChanging(System.Nullable<System.TimeSpan> value);
    partial void OntimesChanged();
    partial void OndateChanging(System.Nullable<System.DateTime> value);
    partial void OndateChanged();
    #endregion
		
		public clock()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clock_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string clock_name
		{
			get
			{
				return this._clock_name;
			}
			set
			{
				if ((this._clock_name != value))
				{
					this.Onclock_nameChanging(value);
					this.SendPropertyChanging();
					this._clock_name = value;
					this.SendPropertyChanged("clock_name");
					this.Onclock_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time_zone", DbType="VarChar(50)")]
		public string time_zone
		{
			get
			{
				return this._time_zone;
			}
			set
			{
				if ((this._time_zone != value))
				{
					this.Ontime_zoneChanging(value);
					this.SendPropertyChanging();
					this._time_zone = value;
					this.SendPropertyChanged("time_zone");
					this.Ontime_zoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_times", DbType="Time")]
		public System.Nullable<System.TimeSpan> times
		{
			get
			{
				return this._times;
			}
			set
			{
				if ((this._times != value))
				{
					this.OntimesChanging(value);
					this.SendPropertyChanging();
					this._times = value;
					this.SendPropertyChanged("times");
					this.OntimesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="Date")]
		public System.Nullable<System.DateTime> date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HMS")]
	public partial class HM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Country;
		
		private int _H;
		
		private int _M;
		
		private int _S;
		
		private string _AM_Pm;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCountryChanging(string value);
    partial void OnCountryChanged();
    partial void OnHChanging(int value);
    partial void OnHChanged();
    partial void OnMChanging(int value);
    partial void OnMChanged();
    partial void OnSChanging(int value);
    partial void OnSChanged();
    partial void OnAM_PmChanging(string value);
    partial void OnAM_PmChanged();
    #endregion
		
		public HM()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Country
		{
			get
			{
				return this._Country;
			}
			set
			{
				if ((this._Country != value))
				{
					this.OnCountryChanging(value);
					this.SendPropertyChanging();
					this._Country = value;
					this.SendPropertyChanged("Country");
					this.OnCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_H", DbType="Int NOT NULL")]
		public int H
		{
			get
			{
				return this._H;
			}
			set
			{
				if ((this._H != value))
				{
					this.OnHChanging(value);
					this.SendPropertyChanging();
					this._H = value;
					this.SendPropertyChanged("H");
					this.OnHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_M", DbType="Int NOT NULL")]
		public int M
		{
			get
			{
				return this._M;
			}
			set
			{
				if ((this._M != value))
				{
					this.OnMChanging(value);
					this.SendPropertyChanging();
					this._M = value;
					this.SendPropertyChanged("M");
					this.OnMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S", DbType="Int NOT NULL")]
		public int S
		{
			get
			{
				return this._S;
			}
			set
			{
				if ((this._S != value))
				{
					this.OnSChanging(value);
					this.SendPropertyChanging();
					this._S = value;
					this.SendPropertyChanged("S");
					this.OnSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AM_Pm", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string AM_Pm
		{
			get
			{
				return this._AM_Pm;
			}
			set
			{
				if ((this._AM_Pm != value))
				{
					this.OnAM_PmChanging(value);
					this.SendPropertyChanging();
					this._AM_Pm = value;
					this.SendPropertyChanged("AM_Pm");
					this.OnAM_PmChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SetAlarm")]
	public partial class SetAlarm : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _H;
		
		private int _M;
		
		private int _S;
		
		private System.Nullable<int> _yes_no;
		
		private string _AM_Pm;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnHChanging(int value);
    partial void OnHChanged();
    partial void OnMChanging(int value);
    partial void OnMChanged();
    partial void OnSChanging(int value);
    partial void OnSChanged();
    partial void Onyes_noChanging(System.Nullable<int> value);
    partial void Onyes_noChanged();
    partial void OnAM_PmChanging(string value);
    partial void OnAM_PmChanged();
    #endregion
		
		public SetAlarm()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_H", DbType="Int NOT NULL")]
		public int H
		{
			get
			{
				return this._H;
			}
			set
			{
				if ((this._H != value))
				{
					this.OnHChanging(value);
					this.SendPropertyChanging();
					this._H = value;
					this.SendPropertyChanged("H");
					this.OnHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_M", DbType="Int NOT NULL")]
		public int M
		{
			get
			{
				return this._M;
			}
			set
			{
				if ((this._M != value))
				{
					this.OnMChanging(value);
					this.SendPropertyChanging();
					this._M = value;
					this.SendPropertyChanged("M");
					this.OnMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S", DbType="Int NOT NULL")]
		public int S
		{
			get
			{
				return this._S;
			}
			set
			{
				if ((this._S != value))
				{
					this.OnSChanging(value);
					this.SendPropertyChanging();
					this._S = value;
					this.SendPropertyChanged("S");
					this.OnSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_yes_no", DbType="Int")]
		public System.Nullable<int> yes_no
		{
			get
			{
				return this._yes_no;
			}
			set
			{
				if ((this._yes_no != value))
				{
					this.Onyes_noChanging(value);
					this.SendPropertyChanging();
					this._yes_no = value;
					this.SendPropertyChanged("yes_no");
					this.Onyes_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AM_Pm", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string AM_Pm
		{
			get
			{
				return this._AM_Pm;
			}
			set
			{
				if ((this._AM_Pm != value))
				{
					this.OnAM_PmChanging(value);
					this.SendPropertyChanging();
					this._AM_Pm = value;
					this.SendPropertyChanged("AM_Pm");
					this.OnAM_PmChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SetAlarm")]
	public partial class SetAlarm1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _H;
		
		private int _M;
		
		private int _S;
		
		private System.Nullable<int> _yes_no;
		
		private string _AM_Pm;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnHChanging(int value);
    partial void OnHChanged();
    partial void OnMChanging(int value);
    partial void OnMChanged();
    partial void OnSChanging(int value);
    partial void OnSChanged();
    partial void Onyes_noChanging(System.Nullable<int> value);
    partial void Onyes_noChanged();
    partial void OnAM_PmChanging(string value);
    partial void OnAM_PmChanged();
    #endregion
		
		public SetAlarm1()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_H", DbType="Int NOT NULL")]
		public int H
		{
			get
			{
				return this._H;
			}
			set
			{
				if ((this._H != value))
				{
					this.OnHChanging(value);
					this.SendPropertyChanging();
					this._H = value;
					this.SendPropertyChanged("H");
					this.OnHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_M", DbType="Int NOT NULL")]
		public int M
		{
			get
			{
				return this._M;
			}
			set
			{
				if ((this._M != value))
				{
					this.OnMChanging(value);
					this.SendPropertyChanging();
					this._M = value;
					this.SendPropertyChanged("M");
					this.OnMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S", DbType="Int NOT NULL")]
		public int S
		{
			get
			{
				return this._S;
			}
			set
			{
				if ((this._S != value))
				{
					this.OnSChanging(value);
					this.SendPropertyChanging();
					this._S = value;
					this.SendPropertyChanged("S");
					this.OnSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_yes_no", DbType="Int")]
		public System.Nullable<int> yes_no
		{
			get
			{
				return this._yes_no;
			}
			set
			{
				if ((this._yes_no != value))
				{
					this.Onyes_noChanging(value);
					this.SendPropertyChanging();
					this._yes_no = value;
					this.SendPropertyChanged("yes_no");
					this.Onyes_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AM_Pm", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string AM_Pm
		{
			get
			{
				return this._AM_Pm;
			}
			set
			{
				if ((this._AM_Pm != value))
				{
					this.OnAM_PmChanging(value);
					this.SendPropertyChanging();
					this._AM_Pm = value;
					this.SendPropertyChanged("AM_Pm");
					this.OnAM_PmChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.World_Clock")]
	public partial class World_Clock : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Country;
		
		private System.Nullable<int> _H;
		
		private System.Nullable<int> _M;
		
		private System.Nullable<int> _S;
		
		private string _PA;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCountryChanging(string value);
    partial void OnCountryChanged();
    partial void OnHChanging(System.Nullable<int> value);
    partial void OnHChanged();
    partial void OnMChanging(System.Nullable<int> value);
    partial void OnMChanged();
    partial void OnSChanging(System.Nullable<int> value);
    partial void OnSChanged();
    partial void OnPAChanging(string value);
    partial void OnPAChanged();
    #endregion
		
		public World_Clock()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Country
		{
			get
			{
				return this._Country;
			}
			set
			{
				if ((this._Country != value))
				{
					this.OnCountryChanging(value);
					this.SendPropertyChanging();
					this._Country = value;
					this.SendPropertyChanged("Country");
					this.OnCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_H", DbType="Int")]
		public System.Nullable<int> H
		{
			get
			{
				return this._H;
			}
			set
			{
				if ((this._H != value))
				{
					this.OnHChanging(value);
					this.SendPropertyChanging();
					this._H = value;
					this.SendPropertyChanged("H");
					this.OnHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_M", DbType="Int")]
		public System.Nullable<int> M
		{
			get
			{
				return this._M;
			}
			set
			{
				if ((this._M != value))
				{
					this.OnMChanging(value);
					this.SendPropertyChanging();
					this._M = value;
					this.SendPropertyChanged("M");
					this.OnMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S", DbType="Int")]
		public System.Nullable<int> S
		{
			get
			{
				return this._S;
			}
			set
			{
				if ((this._S != value))
				{
					this.OnSChanging(value);
					this.SendPropertyChanging();
					this._S = value;
					this.SendPropertyChanged("S");
					this.OnSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PA", DbType="VarChar(50)")]
		public string PA
		{
			get
			{
				return this._PA;
			}
			set
			{
				if ((this._PA != value))
				{
					this.OnPAChanging(value);
					this.SendPropertyChanging();
					this._PA = value;
					this.SendPropertyChanged("PA");
					this.OnPAChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Namaz_Timer")]
	public partial class Namaz_Timer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Namaz_Name;
		
		private string _Timing;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNamaz_NameChanging(string value);
    partial void OnNamaz_NameChanged();
    partial void OnTimingChanging(string value);
    partial void OnTimingChanged();
    #endregion
		
		public Namaz_Timer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Namaz_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Namaz_Name
		{
			get
			{
				return this._Namaz_Name;
			}
			set
			{
				if ((this._Namaz_Name != value))
				{
					this.OnNamaz_NameChanging(value);
					this.SendPropertyChanging();
					this._Namaz_Name = value;
					this.SendPropertyChanged("Namaz_Name");
					this.OnNamaz_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Timing", DbType="VarChar(50)")]
		public string Timing
		{
			get
			{
				return this._Timing;
			}
			set
			{
				if ((this._Timing != value))
				{
					this.OnTimingChanging(value);
					this.SendPropertyChanging();
					this._Timing = value;
					this.SendPropertyChanged("Timing");
					this.OnTimingChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.loginn")]
	public partial class loginn : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _USER_REG;
		
		private System.Nullable<int> _userpass;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUSER_REGChanging(string value);
    partial void OnUSER_REGChanged();
    partial void OnuserpassChanging(System.Nullable<int> value);
    partial void OnuserpassChanged();
    #endregion
		
		public loginn()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_REG", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string USER_REG
		{
			get
			{
				return this._USER_REG;
			}
			set
			{
				if ((this._USER_REG != value))
				{
					this.OnUSER_REGChanging(value);
					this.SendPropertyChanging();
					this._USER_REG = value;
					this.SendPropertyChanged("USER_REG");
					this.OnUSER_REGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userpass", DbType="Int")]
		public System.Nullable<int> userpass
		{
			get
			{
				return this._userpass;
			}
			set
			{
				if ((this._userpass != value))
				{
					this.OnuserpassChanging(value);
					this.SendPropertyChanging();
					this._userpass = value;
					this.SendPropertyChanged("userpass");
					this.OnuserpassChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
